#!/bin/bash

# Author: Quinn Bruckmann
# Date Created: 05/05/2025
# Last Modified: 05/05/2025

# Description
# Prints "Hello World!

# Usage
# first_script

#This is a comment

echo $"Hello World!"
exit 0
