#!/bin/bash

# Author Quinn Bruckmann
# Date Created: 10/05/2025
# Date Last Modified: 10/05/2025
# Description: Takes an operation char, then up to nine numbers to apply the operator on
# Usage: ./pos_params_proj + 1 2 3 4 5 6 7 8 9

default=0

value=$((${2-unset} $1 ${3-unset} $1 ${4-unset} $1 ${5-unset} $1 ${6-unset} $1 ${7-unset} $1 ${8-unset} $1 ${9-unset} $1 ${10-0}))

echo $value


exit 0
